// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpWoI8DPV8nVGzWa1ewrIAycjvuABB8j0',
    appId: '1:760093085901:android:2e4eb0634e45d18962d984',
    messagingSenderId: '760093085901',
    projectId: 'gasleaksignin',
    storageBucket: 'gasleaksignin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk0spUM0nKAOPaOyJJ5G85YeLgKaap-l8',
    appId: '1:760093085901:ios:b1e0aaf46231f39e62d984',
    messagingSenderId: '760093085901',
    projectId: 'gasleaksignin',
    storageBucket: 'gasleaksignin.appspot.com',
    androidClientId: '760093085901-3h1ogqubmrapt85o2m33d5htl7jprg6r.apps.googleusercontent.com',
    iosClientId: '760093085901-35r74vjce3pore7tm04s33c8djot2v8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasLeakDetector',
  );
}
